In [1]:
import numpy as np

In [3]:
Array = np.linspace(1,5,3)
Array

array([1., 3., 5.])

In [4]:
Array = np.random.random((2,3))
Array

array([[0.8455365 , 0.67892692, 0.30086195],
       [0.71919884, 0.08856941, 0.18975115]])

In [6]:
Array = np.zeros((2,3))
Array

array([[0., 0., 0.],
       [0., 0., 0.]])

In [8]:
Array[0:2]

array([[0., 0., 0.],
       [0., 0., 0.]])

In [23]:
ls = ([1,2,3,4])
ls2 = ([2,3,4,5])

In [27]:
np.multiply(ls,ls2)

array([ 2,  6, 12, 20])

In [28]:
Array = np.array([(8,9,10),(11,12,13)])
Array

array([[ 8,  9, 10],
       [11, 12, 13]])

In [39]:
Array = Array.reshape(3,2)
Array

array([[ 8,  9],
       [10, 11],
       [12, 13]])

In [41]:
Array.flatten() #c-style

array([ 8,  9, 10, 11, 12, 13])

In [43]:
Array.flatten('F') #Fortran-style

array([ 8, 10, 12,  9, 11, 13])